coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        informational: true
        after_n_builds: 4
    patch:
      default:
        informational: true

flags:
  sqlite-bruteforce:
    paths:
      - "internal/"
      - "cmd/"
    carryforward: true
  sqlite-hnsw:
    paths:
      - "internal/"
      - "cmd/"
    carryforward: true
  qdrant:
    paths:
      - "internal/"
      - "cmd/"
    carryforward: true
  postgres:
    paths:
      - "internal/"
      - "cmd/"
    carryforward: true

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
