version: "2"

run:
  timeout: 5m
  build-tags:
    - sqlite_fts5
    - sqlite
    - bruteforce
    - hnsw
    - postgres
    - pgvector
    - qdrant

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosec
    - revive
    - ineffassign
    - unused
