import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar for the Shaktiman documentation site.
 *
 * Step 4 of the rollout will replace the autogenerated sidebar with a
 * hand-ordered manual sidebar (Getting Started → Guides → Examples →
 * Integrations → Configuration → Performance → Migrating → Reference →
 * Troubleshooting → Design → Contributing → Changelog). For now, while
 * content is being authored, auto-generation keeps the site buildable.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
